DROP TABLE IF EXISTS regions;
CREATE TABLE regions (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE InnoDB;

DROP TABLE IF EXISTS cities;
CREATE TABLE cities (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(255) NOT NULL UNIQUE,
    regions_id INT NOT NULL, 
    active BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (regions_id) REFERENCES regions(id)
) ENGINE InnoDB;
